### PR TITLE
extract_paths more efficient

### PR DESCRIPTION
**Pull request by albertz**
This gives me some huge speedup, of a big GMM pipeline, from 18 sec runtime down to 12 sec runtime.

### CODE REVIEW

**Comment by albertz** [comment]
> This PR breaks my setups, we have to revert this.

@JackTemaki  Can you give some details?

**Comment by JackTemaki** [comment]
> > This PR breaks my setups, we have to revert this.
> 
> @JackTemaki Can you give some details?

Not yet, just that nearly all of the dependencies are lost. I now have to start debugging.

**Comment by albertz** [comment]
Ah I think I know. This is probably because there are temp `tuple` objects created (via whatever `__sis_state__` or `__getstate__` you have) and then they are deleted again and so we have the same `id(obj)` for different objects...

**Comment by albertz** [comment]
Ok I will try to fix this.

**Comment by albertz** [comment]
@JackTemaki Ok I think I fixed it, see #89.

**Pull request merged**
