### PR TITLE
ask for automatic creation of job when running worker

### PR DESCRIPTION
**Pull request by JackTemaki**
Sometimes when you run a job manually with the worker you forgot to actually create the job over the console first. As his happens more often, I though it might be nice to try to create the job if it does not exist when running the worker.

### CODE REVIEW

**Comment by curufinwe** [comment]
There is only one problem with this. It only works when you use the default config name. If you have different config names, how will the worker know which config-file to load?

**Comment by JackTemaki** [comment]
> There is only one problem with this. It only works when you use the default config name. If you have different config names, how will the worker know which config-file to load?

The cleaner also does not work when using multiple config files, so I think it is okay to not cover this. I do not see how this can be integrated that easily. I think it is best practice to configure the setup in a way that all configs are loaded when not specifying one.

**Comment by critias** [comment]
I also don't like that it only works if the default config is used.
tk.job_run (https://github.com/rwth-i6/sisyphus/blob/master/sisyphus/toolkit.py#L312) does already something similar. 
How about expanding that function to accept also strings instead of only Jobs?
The function could the be directly called from the system shell using the -c flag, but this is not very convenient. Maybe we should consider add a short cut to access some functions of the toolkit directly.

**Comment by critias** [comment]
The cleaner isn't working with multiple config files? I'm too busy this month to look into it, but that's a bug which should be fixed.

**Comment by JackTemaki** [comment]
> The cleaner isn't working with multiple config files? I'm too busy this month to look into it, but that's a bug which should be fixed.

It does, but you always have to give all configs then, otherwise it will delete Jobs of configs not specified, or was this changed? At least when I tried it a long time ago this was the behavior I think...

**Comment by curufinwe** [comment]
> > The cleaner isn't working with multiple config files? I'm too busy this month to look into it, but that's a bug which should be fixed.
> 
> It does, but you always have to give all configs then, otherwise it will delete Jobs of configs not specified, or was this changed? At least when I tried it a long time ago this was the behavior I think...

And this should be the default behaviour. You could have different python scripts in the root folder, so we cannot reliably determine which python files are sisyphus configs.

**Comment by critias** [comment]
Yes, so cleaning working with multiple configs, but you need to load all configures for sisyphus to know which jobs it should keep. Maybe we should add a warning to remind users about that?

So back to topic: I agree that having this feature would be nice, but it should not only work for the default config.

**Pull request closed without merging**
